trigger:
- master

pool:
  name: 'container-poc'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'k8sregistry'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'container-poc-k8s'
    azureResourceGroup: 'gov-devops'
    kubernetesCluster: 'aksport'
    command: 'apply'
    arguments: '-f deploy.yaml'